[workspace]
members = ["dotenv-ng", "dotenv-ng-core", "dotenv-ng-macros", "examples/*"]
resolver = "2"

[workspace.package]
version = "1.0.0"
edition = "2021"
rust-version = "1.74.0"
license = "MIT"
categories = ["configuration"]
homepage = "https://github.com/cachix/dotenv-ng"
keywords = ["dotenv", "env", "environment", "settings", "config"]
repository = "https://github.com/cachix/dotenv-ng"
authors = ["Domen Kožar <domen@cachix.org>"]

[workspace.lints.clippy]
all = "deny"
pedantic = "deny"
nursery = "deny"
cargo = "deny"

[workspace.dependencies]
proc-macro2 = "1"
quote = "1"
syn = "2"
